dataset: imagenet
model_name: "inception_v3.tv_in1k"
batch_size: 500
n_examples: 5000

threat_model: Linf

attacker_name: ReACG
n_targets: 9
param:
  epsilon: 0.015686275
  momentum_alpha: 0.75
  initial_stepsize: 0.03137255
  odi_step: 0.015686275
  max_iter: 5
  criterion_name: cw
  normalization: sign
  rho: 0.75
  move_to_best: true
  odi_iter: 2
  n_restarts: 1
  use_cw_value: false
  beta: HS
  scaling_method: norm # or norm or zero
  scaling_constant: 100000
  use_linstep: false
  a: 0.43 # p_1
  b: 0.24 # q
  c: 0.08 # q_{min}
  use_clamp: false
  initial_point: input