dataset: imagenet
model_name: "inception_v3.tv_in1k"
batch_size: 500
n_examples: 5000

threat_model: Linf

attacker_name: APGD
n_targets: 9
param:
  epsilon: 0.1254902
  momentum_alpha: 0.75
  initial_stepsize: 0.2509804
  odi_step: 0.1254902
  initial_point: center
  max_iter: 100
  criterion_name: cw
  normalization: sign
  rho: 0.75
  move_to_best: true
  odi_iter: 2
  n_restarts: 1
  use_cw_value: false