# The same settings in ACG paper
dataset: imagenet
model_name: Peng2023Robust
batch_size: 20
n_examples: 5000

threat_model: Linf

attacker_name: ACG
n_targets: 9
param:
  epsilon: 0.03137254901960784
  max_iter: 100
  criterion_name: cw
  initial_stepsize: 0.062745098039216
  beta: HS
  use_clamp: false
  normalization: sign
  rho: 0.75
  move_to_best: true
  # initial_point: center
  initial_point: input
  odi_iter: 2
  odi_step: 0.03137254901960784
  n_restarts: 1
  use_cw_value: false
  a: 0.22 # p_1
  b: 0.03 # q
  c: 0.06 # q_{min}