dataset: imagenet
model_name: "inception_v3.tv_in1k"
batch_size: 500
n_examples: 5000

threat_model: Linf

attacker_name: ACG
n_targets: 9
param:
  epsilon: 0.031372549
  max_iter: 10
  criterion_name: cw
  initial_stepsize: 0.062745098
  beta: HS
  use_clamp: false
  normalization: sign
  rho: 0.75
  move_to_best: true
  # initial_point: center
  initial_point: input
  odi_iter: 2
  odi_step: 0.031372549
  n_restarts: 1
  use_cw_value: false
  a: 0.22 # p_1
  b: 0.03 # q
  c: 0.06 # q_{min}